name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 18
      - run: npm install
      - run: npx expo run:android --no-bundler
      - uses: actions/upload-artifact@v5
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/*.apk
